[project]
name = "lask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["requests>=2.32.3", "setuptools>=80.8.0"]
classifiers = ["Private :: Do Not Upload"]

[project.scripts]
lask = "lask:main"
