name: "Ruff check"

on:
  pull_request:

jobs:
  build:
    name: Ruff check 🦺
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install 3.13 # Or whatever version I want to use.

      - name: Run Ruff check
        run: uv run ruff check

      - name: Run Ruff format
        run: uv run ruff format --diff
